import { TrendingItem } from './types'

export const mockTrends: TrendingItem[] = [
  {
    id: '1',
    title: 'shadcn/ui',
    url: 'https://github.com/shadcn/ui',
    source: 'github',
    author: 'shadcn',
    description: 'Beautifully designed components built with Radix UI and Tailwind CSS.',
    language: 'TypeScript',
    stars: 45678,
    comments: 234,
    category: 'repository',
    scrapedAt: new Date(),
    momentum: 'high',
    isNew: true,
  },
  {
    id: '2',
    title: 'Show HN: I built a CLI tool for managing dotfiles with style',
    url: 'https://news.ycombinator.com/item?id=123456',
    source: 'hackernews',
    author: 'techie_dev',
    description: 'A modern approach to dotfile management with version control and easy restoration.',
    score: 512,
    comments: 87,
    category: 'discussion',
    scrapedAt: new Date(),
    momentum: 'high',
  },
  {
    id: '3',
    title: 'Understanding Rust\'s Ownership Model in 10 Minutes',
    url: 'https://dev.to/rustdev/understanding-rust-ownership',
    source: 'devto',
    author: 'rustdev',
    description: 'A comprehensive guide to Rust\'s most important feature explained simply.',
    reactions: 245,
    comments: 34,
    category: 'article',
    scrapedAt: new Date(),
    momentum: 'medium',
  },
  {
    id: '4',
    title: 'vercel/next.js',
    url: 'https://github.com/vercel/next.js',
    source: 'github',
    author: 'vercel',
    description: 'The React Framework for the Web. Used by some of the world\'s largest companies.',
    language: 'JavaScript',
    stars: 118234,
    comments: 3421,
    category: 'repository',
    scrapedAt: new Date(),
    momentum: 'high',
    isNew: false,
  },
  {
    id: '5',
    title: 'Ask HN: What are you working on?',
    url: 'https://news.ycombinator.com/item?id=789012',
    source: 'hackernews',
    author: 'curious_dev',
    description: 'Monthly thread for sharing side projects and getting feedback from the community.',
    score: 342,
    comments: 456,
    category: 'discussion',
    scrapedAt: new Date(),
    momentum: 'medium',
  },
  {
    id: '6',
    title: 'Building a Real-Time Chat App with WebSockets',
    url: 'https://dev.to/webdev/realtime-chat-websockets',
    source: 'devto',
    author: 'webdev_pro',
    description: 'Step-by-step tutorial for creating a production-ready chat application.',
    reactions: 189,
    comments: 23,
    category: 'article',
    scrapedAt: new Date(),
    momentum: 'low',
  },
  {
    id: '7',
    title: 'microsoft/vscode',
    url: 'https://github.com/microsoft/vscode',
    source: 'github',
    author: 'microsoft',
    description: 'Visual Studio Code - Open source code editor redefined and optimized for building and debugging modern web and cloud applications.',
    language: 'TypeScript',
    stars: 156789,
    comments: 8901,
    category: 'repository',
    scrapedAt: new Date(),
    momentum: 'medium',
  },
  {
    id: '8',
    title: 'The State of JavaScript 2024 Results Are Out',
    url: 'https://news.ycombinator.com/item?id=345678',
    source: 'hackernews',
    author: 'js_enthusiast',
    description: 'Annual survey results showing trends in JavaScript frameworks, tools, and technologies.',
    score: 891,
    comments: 234,
    category: 'discussion',
    scrapedAt: new Date(),
    momentum: 'high',
  },
  {
    id: '9',
    title: 'Mastering CSS Grid Layout in 2024',
    url: 'https://dev.to/cssmaster/css-grid-2024',
    source: 'devto',
    author: 'cssmaster',
    description: 'Everything you need to know about CSS Grid with modern examples and best practices.',
    reactions: 312,
    comments: 45,
    category: 'article',
    scrapedAt: new Date(),
    momentum: 'medium',
  },
]
